# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:14.04

pipelines:
  default:
    - step:
        script:
          - apt-get -qq -y --force-yes update
          - apt-get -y --force-yes install cmake cmake-data gcc-4.9 g++-4.9 xorg-dev libglu1-mesa-dev libxrandr-dev
          - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
          - git submodule update --init --recursive
          - mkdir build
          - cd build
          - cmake ..
          - make -j2